export const sagaActions = {
    GET_HEROES: "GET_HEROES",
    GET_HERO_BY_ID: "GET_HERO_BY_ID",
    CREATE_HERO: "CREATE_HERO",
    EDIT_HERO: "EDIT_HERO",
    DELETE_HERO: "DELETE_HERO",
    DELETE_IMAGE: "DELETE_IMAGE"
}